using System;
using System.IO;
using System.Linq;
using System.Reflection;

using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.DependencyInjection;

namespace SystemLibrary.Common.Web.Extensions;

partial class IServiceCollectionExtensions
{
    public static IServiceCollection AutoGenerateDataProtectionKeyFile(this IServiceCollection services, CommonWebApplicationServicesOptions options)
    {
        if (!options.AutoGenerateDataProtectionKeyFile) return services;

        var type = Type.GetType("SystemLibrary.Common.Net.CryptationKeyFile, SystemLibrary.Common.Net");
        
        if (type == null)
            throw new Exception("SystemLibrary.Common.Net.CryptationKeyFile is not loaded or type is renamed in version you are using");

        var method = type.GetMethods(BindingFlags.Static | BindingFlags.NonPublic)
            .Where(x => x.Name == "GetKeyFileFullName")
            .FirstOrDefault();

        if (method == null)
            throw new Exception("Method 'GetKeyFileFullName' is renamed or do not exist");

        var baseDirectory = AppContext.BaseDirectory;

        var keyFullFileName = method.Invoke(null, new object[] { baseDirectory }) + "";

        var hasCryptationKeyFile = keyFullFileName.Is();

        var appName = "AppName" + Assembly.GetEntryAssembly()?.FullName + (hasCryptationKeyFile ? keyFullFileName : baseDirectory);

        var rootDirectory = new DirectoryInfo(baseDirectory);

        var builder = services.AddDataProtection();

        if (hasCryptationKeyFile)
        {
            rootDirectory = new DirectoryInfo(Path.GetFullPath(keyFullFileName));

            builder.DisableAutomaticKeyGeneration();
        }

        builder.PersistKeysToFileSystem(rootDirectory)
            .SetDefaultKeyLifetime(TimeSpan.FromDays(365 * 100))
            .SetApplicationName(appName);

        return services;
    }
}